version = 0.1

[default.deploy.parameters]
stack_name = "hackoverflow-backend"
resolve_s3 = true
s3_prefix = "hackoverflow-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FrontendURL=\"https://hackoverflow.srkrcodingclub.in\" CloudinaryCloudName=\"dezojp2j2\" FromEmail=\"srkrcodingclubofficial@gmail.com\""
image_repositories = ["HackOverflowAPI=161266029104.dkr.ecr.ap-south-1.amazonaws.com/hackoverflowbackend188ec4fc/hackoverflowapicd4f1e9brepo"]
disable_rollback = true

[default.global.parameters]
region = "ap-south-1"
